const data = {
  products: [
    {
      _id: "1",
      name: "Shirt + pants",
      category: "shirts",
      image: "/images/p1.jpg",
      price: 120,
      countInStock: 10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 1,
      description: "High quality product",
    },
    {
      _id: "2",
      name: "Pants",
      category: "pants",
      image: "/images/p2.jpg",
      price: 60,
      countInStock: 9,
      brand: "Adidas",
      rating: 4.0,
      numReviews: 9,
      description: "Good pants",
    },
    {
      _id: "3",
      name: "Little hat",
      category: "hats",
      image: "/images/p3.jpg",
      price: 40,
      countInStock: 0,
      brand: "North pole",
      rating: 3.5,
      numReviews: 12,
      description: "Warm hat",
    },
    {
      _id: "4",
      name: "Shirt",
      category: "shirts",
      image: "/images/p4.jpg",
      price: 55,
      countInStock: 5,
      brand: "7 for all mind kind",
      rating: 4.7,
      numReviews: 8,
      description: "Long sleeve shirt",
    },
    {
      _id: "5",
      name: "T-Shirt",
      category: "t-shirts",
      image: "/images/p5.jpg",
      price: 29,
      countInStock: 15,
      brand: "Disney",
      rating: 5,
      numReviews: 9,
      description: "Disney yellow shirt",
    },
    {
      _id: "6",
      name: "Shoes",
      category: "shoes",
      image: "/images/p6.jpg",
      price: 89,
      countInStock: 8,
      brand: "Converse",
      rating: 4.0,
      numReviews: 20,
      description: "Black shoes",
    },
  ],
};

export default data;
